import type { Challenge, ChallengeLanguage } from "./types";

const ALGORITHMIC_LANGUAGES: ChallengeLanguage[] = [
  "typescript",
  "javascript",
  "python",
  "java",
  "cpp",
  "go",
  "rust",
];
const CORE_LANGUAGES = ALGORITHMIC_LANGUAGES;
const SCRIPTING_LANGUAGES = ALGORITHMIC_LANGUAGES;
const SYSTEMS_LANGUAGES = ALGORITHMIC_LANGUAGES;

function createStarterCode(
  title: string,
  languages: ChallengeLanguage[],
): Partial<Record<ChallengeLanguage, string>> {
  const starterCode: Record<ChallengeLanguage, string> = {
    typescript: `// ${title}\n// Parse the provided input and return the answer as a string.\nexport function solve(input: string): string {\n  return "";\n}\n`,
    javascript: `// ${title}\n// Parse the provided input and return the answer as a string.\nfunction solve(input) {\n  return "";\n}\n\nmodule.exports = { solve };\n`,
    python: `# ${title}\n# Parse the provided input and return the answer as a string.\ndef solve(input_data: str) -> str:\n    return ""\n`,
    java: `// ${title}\n// Parse the provided input and return the answer as a string.\nclass Solution {\n    public String solve(String input) {\n        return "";\n    }\n}\n`,
    cpp: `// ${title}\n// Parse the provided input and return the answer as a string.\n#include <string>\nusing namespace std;\n\nclass Solution {\npublic:\n    string solve(const string& input) {\n        return "";\n    }\n};\n`,
    go: `// ${title}\n// Parse the provided input and return the answer as a string.\npackage main\n\nfunc Solve(input string) string {\n\treturn ""\n}\n`,
    rust: `// ${title}\n// Parse the provided input and return the answer as a string.\npub fn solve(input: &str) -> String {\n    String::new()\n}\n`,
    sql: `-- ${title}\n-- Write a query that returns the requested result.\nSELECT 1;\n`,
  };

  return languages.reduce<Partial<Record<ChallengeLanguage, string>>>(
    (codeByLanguage, language) => {
      codeByLanguage[language] = starterCode[language];
      return codeByLanguage;
    },
    {},
  );
}

export const CHALLENGE_CATALOG: Challenge[] = [
  {
    id: "challenge-001",
    slug: "signal-stabilizer",
    title: "Signal Stabilizer",
    difficulty: "Easy",
    summary:
      "Find the first reading that keeps a running sensor total within a safe band.",
    description: [
      "A monitoring node receives a stream of signed sensor adjustments. Starting from zero, apply each adjustment in order and track the running total.",
      "Return the zero-based index of the first adjustment after which the running total is inside the inclusive safe band. If the stream never stabilizes, return -1.",
    ],
    examples: [
      {
        title: "Stabilizes after a dip",
        input: "band = [-2, 3], readings = [5, -7, 1, 2]",
        output: "2",
        explanation:
          "The running totals are 5, -2, -1, and 1. Index 2 is the first total inside the band after the out-of-band start.",
      },
      {
        title: "No safe reading",
        input: "band = [4, 6], readings = [1, 1, 1]",
        output: "-1",
      },
    ],
    constraints: [
      "1 <= readings.length <= 100,000",
      "-10,000 <= readings[i] <= 10,000",
      "band[0] <= band[1]",
      "The running total fits in a signed 64-bit integer.",
    ],
    notes: ["A single pass is enough if you update the running total incrementally."],
    tags: ["Array", "Prefix Sum", "Simulation"],
    category: "Warmup",
    kind: "algorithmic",
    supportedLanguages: CORE_LANGUAGES,
    starterCodeByLanguage: createStarterCode("Signal Stabilizer", CORE_LANGUAGES),
    acceptanceRate: 78,
    estimatedMinutes: 12,
    attempts: 18320,
    popularity: 94,
    createdAt: "2026-03-21",
    progress: "solved",
    testCases: [
      {
        name: "Sample 1",
        input: "[-2, 3]\n[5, -7, 1, 2]",
        expectedOutput: "2",
      },
      {
        name: "Sample 2",
        input: "[4, 6]\n[1, 1, 1]",
        expectedOutput: "-1",
      },
    ],
  },
  {
    id: "challenge-002",
    slug: "mirror-log",
    title: "Mirror Log",
    difficulty: "Easy",
    summary: "Check whether a command log reads the same after ignoring separators.",
    description: [
      "A terminal recorder stores commands with spaces, dashes, and timestamps mixed into the stream. For a quick integrity check, only lowercase letters and digits matter.",
      "Return true if the meaningful characters form a palindrome. Character case should be ignored.",
    ],
    examples: [
      {
        title: "Balanced log",
        input: 'log = "Deploy-101 -- yolped"',
        output: "true",
        explanation:
          "The meaningful stream is deploy101yolped, which mirrors around 101.",
      },
      {
        title: "Mismatched log",
        input: 'log = "cache-evict-42"',
        output: "false",
      },
    ],
    constraints: [
      "1 <= log.length <= 200,000",
      "The log may contain letters, digits, spaces, punctuation, and symbols.",
      "Only ASCII alphanumeric characters participate in the check.",
    ],
    notes: ["Use two pointers so the extra memory stays constant."],
    tags: ["String", "Two Pointers"],
    category: "Strings",
    kind: "algorithmic",
    supportedLanguages: SCRIPTING_LANGUAGES,
    starterCodeByLanguage: createStarterCode("Mirror Log", SCRIPTING_LANGUAGES),
    acceptanceRate: 83,
    estimatedMinutes: 10,
    attempts: 14240,
    popularity: 88,
    createdAt: "2026-03-18",
    progress: "in-progress",
    testCases: [
      {
        name: "Sample 1",
        input: "Deploy-101 -- yolped",
        expectedOutput: "true",
      },
      {
        name: "Sample 2",
        input: "cache-evict-42",
        expectedOutput: "false",
      },
    ],
  },
  {
    id: "challenge-003",
    slug: "cache-key-collisions",
    title: "Cache Key Collisions",
    difficulty: "Medium",
    summary: "Group API cache keys that normalize to the same canonical form.",
    description: [
      "A gateway normalizes cache keys before routing them. Normalization lowercases letters and removes underscores.",
      "Given a list of keys, return every canonical form that appears more than once, along with the original keys that produced it. Preserve each group in the order its first collision is discovered.",
    ],
    examples: [
      {
        title: "Two collision groups",
        input: 'keys = ["User_List", "userlist", "Order_Read", "orderread", "orders"]',
        output:
          '[["userlist", ["User_List", "userlist"]], ["orderread", ["Order_Read", "orderread"]]]',
      },
    ],
    constraints: [
      "1 <= keys.length <= 50,000",
      "1 <= keys[i].length <= 80",
      "Keys contain letters, digits, underscores, and dashes.",
      "The total input size is at most 1 MB.",
    ],
    notes: ["A map from normalized key to original keys gives stable grouping."],
    tags: ["Hash Table", "String"],
    category: "Data Structures",
    kind: "algorithmic",
    supportedLanguages: SCRIPTING_LANGUAGES,
    starterCodeByLanguage: createStarterCode("Cache Key Collisions", SCRIPTING_LANGUAGES),
    acceptanceRate: 61,
    estimatedMinutes: 24,
    attempts: 21980,
    popularity: 91,
    createdAt: "2026-03-25",
    progress: "not-started",
    testCases: [
      {
        name: "Sample 1",
        input: "User_List,userlist,Order_Read,orderread,orders",
        expectedOutput: "userlist: User_List userlist\norderread: Order_Read orderread",
      },
    ],
  },
  {
    id: "challenge-004",
    slug: "packet-window-median",
    title: "Packet Window Median",
    difficulty: "Hard",
    summary: "Report the rolling median latency for every fixed-size packet window.",
    description: [
      "A network probe records packet latency in milliseconds. For every contiguous window of size k, compute the median latency.",
      "If k is even, the median is the average of the two middle values. Return medians in window order with one decimal place when needed.",
    ],
    examples: [
      {
        title: "Odd window",
        input: "latency = [7, 2, 9, 4, 1], k = 3",
        output: "[7, 4, 4]",
      },
      {
        title: "Even window",
        input: "latency = [5, 1, 8, 2], k = 2",
        output: "[3, 4.5, 5]",
      },
    ],
    constraints: [
      "1 <= k <= latency.length <= 100,000",
      "0 <= latency[i] <= 1,000,000",
      "Expected complexity is O(n log k).",
    ],
    notes: ["A two-heap structure with lazy deletion keeps each window balanced."],
    tags: ["Heap", "Sliding Window", "Sorting"],
    category: "Advanced",
    kind: "algorithmic",
    supportedLanguages: SYSTEMS_LANGUAGES,
    starterCodeByLanguage: createStarterCode("Packet Window Median", SYSTEMS_LANGUAGES),
    acceptanceRate: 37,
    estimatedMinutes: 45,
    attempts: 16870,
    popularity: 86,
    createdAt: "2026-02-28",
    progress: "locked",
    testCases: [
      {
        name: "Sample 1",
        input: "[7, 2, 9, 4, 1]\n3",
        expectedOutput: "[7, 4, 4]",
      },
      {
        name: "Sample 2",
        input: "[5, 1, 8, 2]\n2",
        expectedOutput: "[3, 4.5, 5]",
      },
    ],
  },
  {
    id: "challenge-005",
    slug: "courier-routes",
    title: "Courier Routes",
    difficulty: "Medium",
    summary: "Find the fewest handoffs needed to move a package through city hubs.",
    description: [
      "A delivery network is modeled as hubs connected by bidirectional handoff lanes. A courier can move across one lane per handoff.",
      "Given the network, a start hub, and a target hub, return the minimum number of handoffs. If the target is unreachable, return -1.",
    ],
    examples: [
      {
        title: "Reachable target",
        input: "hubs = 5, lanes = [[0,1],[1,2],[0,3],[3,4]], start = 0, target = 4",
        output: "2",
      },
    ],
    constraints: [
      "1 <= hubs <= 100,000",
      "0 <= lanes.length <= 200,000",
      "Hubs are numbered from 0 to hubs - 1.",
      "The graph may be disconnected.",
    ],
    notes: ["Breadth-first search is the natural fit for unweighted shortest paths."],
    tags: ["Graph", "Queue"],
    category: "Graphs",
    kind: "algorithmic",
    supportedLanguages: CORE_LANGUAGES,
    starterCodeByLanguage: createStarterCode("Courier Routes", CORE_LANGUAGES),
    acceptanceRate: 64,
    estimatedMinutes: 26,
    attempts: 19510,
    popularity: 89,
    createdAt: "2026-03-08",
    progress: "not-started",
    testCases: [
      {
        name: "Sample 1",
        input: "5\n0 1\n1 2\n0 3\n3 4\n0\n4",
        expectedOutput: "2",
      },
    ],
  },
  {
    id: "challenge-006",
    slug: "build-pipeline-order",
    title: "Build Pipeline Order",
    difficulty: "Medium",
    summary: "Schedule build jobs when some jobs depend on others finishing first.",
    description: [
      "A build farm receives jobs and dependency pairs. A pair [a, b] means job a must finish before job b can start.",
      "Return any valid job order. If the dependencies contain a cycle, return an empty list.",
    ],
    examples: [
      {
        title: "A valid pipeline",
        input: "jobs = 4, dependencies = [[0,1],[0,2],[2,3]]",
        output: "[0, 1, 2, 3]",
        explanation:
          "Job 1 and job 2 can swap positions, as long as 0 appears before both and 2 appears before 3.",
      },
    ],
    constraints: [
      "1 <= jobs <= 80,000",
      "0 <= dependencies.length <= 160,000",
      "Dependencies may include duplicate pairs.",
    ],
    notes: ["Indegree tracking with a queue is a direct way to detect cycles."],
    tags: ["Graph", "DFS", "Queue"],
    category: "Graphs",
    kind: "algorithmic",
    supportedLanguages: CORE_LANGUAGES,
    starterCodeByLanguage: createStarterCode("Build Pipeline Order", CORE_LANGUAGES),
    acceptanceRate: 55,
    estimatedMinutes: 30,
    attempts: 12770,
    popularity: 82,
    createdAt: "2026-03-16",
    progress: "not-started",
    testCases: [
      {
        name: "Sample 1",
        input: "4\n0 1\n0 2\n2 3",
        expectedOutput: "[0, 1, 2, 3]",
      },
    ],
  },
  {
    id: "challenge-007",
    slug: "adaptive-pricing",
    title: "Adaptive Pricing",
    difficulty: "Easy",
    summary: "Choose the best single discount day and recovery day for a product.",
    description: [
      "A store tracks a projected price for the same item over several days. You may discount inventory on one day and restore the price on a later day.",
      "Return the largest possible positive price gain. If no later day improves the price, return 0.",
    ],
    examples: [
      {
        title: "Profitable recovery",
        input: "prices = [12, 7, 10, 5, 13]",
        output: "8",
      },
      {
        title: "No recovery",
        input: "prices = [9, 8, 6]",
        output: "0",
      },
    ],
    constraints: [
      "1 <= prices.length <= 100,000",
      "0 <= prices[i] <= 1,000,000",
      "The discount day must occur before the recovery day.",
    ],
    notes: ["Track the lowest price seen so far while scanning left to right."],
    tags: ["Array", "Math", "Greedy"],
    category: "Warmup",
    kind: "algorithmic",
    supportedLanguages: CORE_LANGUAGES,
    starterCodeByLanguage: createStarterCode("Adaptive Pricing", CORE_LANGUAGES),
    acceptanceRate: 81,
    estimatedMinutes: 14,
    attempts: 26840,
    popularity: 96,
    createdAt: "2026-02-24",
    progress: "solved",
    testCases: [
      {
        name: "Sample 1",
        input: "[12, 7, 10, 5, 13]",
        expectedOutput: "8",
      },
      {
        name: "Sample 2",
        input: "[9, 8, 6]",
        expectedOutput: "0",
      },
    ],
  },
  {
    id: "challenge-008",
    slug: "binary-signal-boundary",
    title: "Binary Signal Boundary",
    difficulty: "Medium",
    summary: "Locate the first index where a sorted signal crosses a threshold.",
    description: [
      "A hardware probe emits a nondecreasing list of signal strengths. You need to find the first reading that is greater than or equal to a threshold.",
      "Return the index of that reading, or the length of the list if every reading is below the threshold.",
    ],
    examples: [
      {
        title: "Threshold found",
        input: "signals = [1, 2, 2, 5, 9], threshold = 5",
        output: "3",
      },
      {
        title: "Insertion at end",
        input: "signals = [1, 3, 4], threshold = 7",
        output: "3",
      },
    ],
    constraints: [
      "0 <= signals.length <= 1,000,000",
      "-1,000,000 <= signals[i], threshold <= 1,000,000",
      "signals is sorted in nondecreasing order.",
    ],
    notes: ["Be precise with the open and closed sides of the search interval."],
    tags: ["Array", "Binary Search"],
    category: "Search",
    kind: "algorithmic",
    supportedLanguages: CORE_LANGUAGES,
    starterCodeByLanguage: createStarterCode("Binary Signal Boundary", CORE_LANGUAGES),
    acceptanceRate: 70,
    estimatedMinutes: 18,
    attempts: 15100,
    popularity: 84,
    createdAt: "2026-03-02",
    progress: "not-started",
    testCases: [
      {
        name: "Sample 1",
        input: "[1, 2, 2, 5, 9]\n5",
        expectedOutput: "3",
      },
    ],
  },
  {
    id: "challenge-009",
    slug: "archive-compression",
    title: "Archive Compression",
    difficulty: "Medium",
    summary: "Remove adjacent duplicate blocks until the archive stream is stable.",
    description: [
      "An archive stream contains lowercase block markers. Whenever k equal markers become adjacent, those k markers are compressed away.",
      "Return the final stream after repeatedly applying compression until no more groups can be removed.",
    ],
    examples: [
      {
        title: "Chain reaction",
        input: 'stream = "abbbaaacc", k = 3',
        output: "a",
        explanation: "bbb and aaa are removed, then cc remains with a single leading a.",
      },
    ],
    constraints: [
      "1 <= stream.length <= 200,000",
      "2 <= k <= 10,000",
      "stream contains lowercase English letters.",
    ],
    notes: ["A stack of character counts avoids rescanning the stream."],
    tags: ["Stack", "String"],
    category: "Strings",
    kind: "algorithmic",
    supportedLanguages: SCRIPTING_LANGUAGES,
    starterCodeByLanguage: createStarterCode("Archive Compression", SCRIPTING_LANGUAGES),
    acceptanceRate: 52,
    estimatedMinutes: 28,
    attempts: 19480,
    popularity: 87,
    createdAt: "2026-03-29",
    progress: "in-progress",
    testCases: [
      {
        name: "Sample 1",
        input: "abbbaaacc\n3",
        expectedOutput: "a",
      },
    ],
  },
  {
    id: "challenge-010",
    slug: "colony-perimeter",
    title: "Colony Perimeter",
    difficulty: "Medium",
    summary: "Measure the exposed edge length of connected occupied cells.",
    description: [
      "A research grid marks occupied colony cells with 1 and empty cells with 0. Cells connect horizontally and vertically.",
      "Return the total perimeter exposed to empty space or the grid boundary across all occupied cells.",
    ],
    examples: [
      {
        title: "Small colony",
        input: "grid = [[1,1,0],[1,0,0],[1,1,1]]",
        output: "14",
      },
    ],
    constraints: [
      "1 <= rows, columns <= 500",
      "grid[r][c] is 0 or 1",
      "The grid may contain multiple disconnected colonies.",
    ],
    notes: ["Each occupied cell starts with four edges; subtract shared edges."],
    tags: ["Graph", "DFS", "Simulation"],
    category: "Graphs",
    kind: "algorithmic",
    supportedLanguages: CORE_LANGUAGES,
    starterCodeByLanguage: createStarterCode("Colony Perimeter", CORE_LANGUAGES),
    acceptanceRate: 67,
    estimatedMinutes: 22,
    attempts: 11430,
    popularity: 78,
    createdAt: "2026-02-18",
    progress: "not-started",
    testCases: [
      {
        name: "Sample 1",
        input: "[[1,1,0],[1,0,0],[1,1,1]]",
        expectedOutput: "14",
      },
    ],
  },
  {
    id: "challenge-011",
    slug: "latency-budget",
    title: "Latency Budget",
    difficulty: "Hard",
    summary: "Maximize completed services without exceeding a total latency budget.",
    description: [
      "A request can pass through optional services. Each service has a latency cost and a value score. You have a fixed latency budget.",
      "Return the maximum total score achievable without exceeding the budget. Each service can be used at most once.",
    ],
    examples: [
      {
        title: "Budgeted selection",
        input: "budget = 7, services = [[3, 6], [4, 7], [5, 8]]",
        output: "13",
        explanation: "Use the services with costs 3 and 4 for a total score of 13.",
      },
    ],
    constraints: [
      "1 <= services.length <= 2,000",
      "1 <= budget <= 20,000",
      "1 <= latencyCost, valueScore <= 10,000",
    ],
    notes: ["A one-dimensional dynamic programming table keeps memory manageable."],
    tags: ["Dynamic Programming", "Array"],
    category: "Optimization",
    kind: "algorithmic",
    supportedLanguages: SYSTEMS_LANGUAGES,
    starterCodeByLanguage: createStarterCode("Latency Budget", SYSTEMS_LANGUAGES),
    acceptanceRate: 41,
    estimatedMinutes: 42,
    attempts: 9310,
    popularity: 81,
    createdAt: "2026-03-31",
    progress: "not-started",
    testCases: [
      {
        name: "Sample 1",
        input: "7\n3 6\n4 7\n5 8",
        expectedOutput: "13",
      },
    ],
  },
  {
    id: "challenge-012",
    slug: "quantum-safe-lock",
    title: "Quantum Safe Lock",
    difficulty: "Hard",
    summary: "Generate the shortest unlock sequence covering every binary pattern.",
    description: [
      "A lock validates access by scanning the latest n bits entered. You need a sequence that causes every possible n-bit pattern to appear at least once.",
      "Return any shortest valid sequence over 0 and 1.",
    ],
    examples: [
      {
        title: "Two-bit lock",
        input: "n = 2",
        output: "00110",
        explanation: "The sequence contains 00, 01, 11, and 10.",
      },
    ],
    constraints: [
      "1 <= n <= 16",
      "The answer length must be 2^n + n - 1.",
      "Any shortest sequence is accepted.",
    ],
    notes: ["Think of states as bit patterns and edges as appended bits."],
    tags: ["Backtracking", "Bit Manipulation", "Graph"],
    category: "Advanced",
    kind: "algorithmic",
    supportedLanguages: SYSTEMS_LANGUAGES,
    starterCodeByLanguage: createStarterCode("Quantum Safe Lock", SYSTEMS_LANGUAGES),
    acceptanceRate: 33,
    estimatedMinutes: 50,
    attempts: 6020,
    popularity: 73,
    createdAt: "2026-04-04",
    progress: "locked",
    testCases: [
      {
        name: "Sample 1",
        input: "2",
        expectedOutput: "00110",
      },
    ],
  },
  {
    id: "challenge-013",
    slug: "priority-inbox",
    title: "Priority Inbox",
    difficulty: "Easy",
    summary: "Return the k highest priority tickets while preserving clear ordering.",
    description: [
      "A support inbox stores tickets with a numeric priority. Higher numbers should be handled first.",
      "Return the ids of the k highest priority tickets, ordered by priority descending and then by smaller id for ties.",
    ],
    examples: [
      {
        title: "Tie by id",
        input: "tickets = [[7, 40], [3, 50], [9, 50]], k = 2",
        output: "[3, 9]",
      },
    ],
    constraints: [
      "1 <= tickets.length <= 100,000",
      "1 <= k <= tickets.length",
      "Ticket ids are unique positive integers.",
    ],
    notes: ["Sorting is acceptable; a heap is useful when k is much smaller than n."],
    tags: ["Heap", "Sorting"],
    category: "Data Structures",
    kind: "algorithmic",
    supportedLanguages: CORE_LANGUAGES,
    starterCodeByLanguage: createStarterCode("Priority Inbox", CORE_LANGUAGES),
    acceptanceRate: 74,
    estimatedMinutes: 16,
    attempts: 8360,
    popularity: 76,
    createdAt: "2026-02-11",
    progress: "not-started",
    testCases: [
      {
        name: "Sample 1",
        input: "7 40\n3 50\n9 50\n2",
        expectedOutput: "[3, 9]",
      },
    ],
  },
  {
    id: "challenge-014",
    slug: "trade-ledger-balance",
    title: "Trade Ledger Balance",
    difficulty: "Medium",
    summary: "Find the longest period where account inflows and outflows balance.",
    description: [
      "A ledger marks each transaction as +1 for an inflow and -1 for an outflow. A balanced period has a net sum of zero.",
      "Return the length of the longest contiguous balanced period.",
    ],
    examples: [
      {
        title: "Long balanced span",
        input: "ledger = [1, -1, -1, 1, 1, -1]",
        output: "6",
      },
      {
        title: "Partial span",
        input: "ledger = [1, 1, -1, 1]",
        output: "2",
      },
    ],
    constraints: [
      "1 <= ledger.length <= 200,000",
      "ledger[i] is either 1 or -1",
      "Expected complexity is O(n).",
    ],
    notes: ["Store the earliest index where each prefix sum appears."],
    tags: ["Prefix Sum", "Hash Table", "Array"],
    category: "Data Structures",
    kind: "algorithmic",
    supportedLanguages: SCRIPTING_LANGUAGES,
    starterCodeByLanguage: createStarterCode("Trade Ledger Balance", SCRIPTING_LANGUAGES),
    acceptanceRate: 59,
    estimatedMinutes: 25,
    attempts: 12380,
    popularity: 80,
    createdAt: "2026-03-12",
    progress: "not-started",
    testCases: [
      {
        name: "Sample 1",
        input: "[1, -1, -1, 1, 1, -1]",
        expectedOutput: "6",
      },
    ],
  },
  {
    id: "challenge-015",
    slug: "unioned-accounts",
    title: "Unioned Accounts",
    difficulty: "Medium",
    summary: "Merge account records that share at least one verified email address.",
    description: [
      "Each account record contains a display name followed by one or more verified email addresses. Records with any shared email belong to the same person.",
      "Return merged accounts with the display name from the first record in each group and sorted unique emails.",
    ],
    examples: [
      {
        title: "Shared email merge",
        input:
          'accounts = [["Rin","r@cf.dev","rin@cf.dev"],["Kai","k@cf.dev"],["Rin","rin@cf.dev","ops@cf.dev"]]',
        output: '[["Rin","ops@cf.dev","r@cf.dev","rin@cf.dev"],["Kai","k@cf.dev"]]',
      },
    ],
    constraints: [
      "1 <= accounts.length <= 20,000",
      "1 <= emails per account <= 20",
      "Email strings are lowercase and unique within a single record.",
    ],
    notes: ["Union-Find keeps connected records cheap to merge."],
    tags: ["Union-Find", "Hash Table", "Sorting"],
    category: "Data Structures",
    kind: "algorithmic",
    supportedLanguages: CORE_LANGUAGES,
    starterCodeByLanguage: createStarterCode("Unioned Accounts", CORE_LANGUAGES),
    acceptanceRate: 48,
    estimatedMinutes: 34,
    attempts: 13820,
    popularity: 83,
    createdAt: "2026-02-20",
    progress: "in-progress",
    testCases: [
      {
        name: "Sample 1",
        input: "Rin r@cf.dev rin@cf.dev\nKai k@cf.dev\nRin rin@cf.dev ops@cf.dev",
        expectedOutput: "Rin ops@cf.dev r@cf.dev rin@cf.dev\nKai k@cf.dev",
      },
    ],
  },
  {
    id: "challenge-016",
    slug: "sensor-drift",
    title: "Sensor Drift",
    difficulty: "Easy",
    summary: "Find the smallest moving average that crosses an alert threshold.",
    description: [
      "A lab sensor reports integer readings every second. For each window of size k, compute the average reading.",
      "Return the first window start index whose average is greater than or equal to the alert threshold. If no window qualifies, return -1.",
    ],
    examples: [
      {
        title: "Alert crossed",
        input: "readings = [2, 3, 8, 4, 6], k = 3, threshold = 5",
        output: "1",
      },
      {
        title: "No alert",
        input: "readings = [1, 2, 3], k = 2, threshold = 5",
        output: "-1",
      },
    ],
    constraints: [
      "1 <= k <= readings.length <= 100,000",
      "-10,000 <= readings[i] <= 10,000",
      "threshold may be fractional.",
    ],
    notes: ["Compare sums against threshold * k to avoid repeated division."],
    tags: ["Sliding Window", "Math", "Array"],
    category: "Warmup",
    kind: "algorithmic",
    supportedLanguages: SCRIPTING_LANGUAGES,
    starterCodeByLanguage: createStarterCode("Sensor Drift", SCRIPTING_LANGUAGES),
    acceptanceRate: 76,
    estimatedMinutes: 15,
    attempts: 10220,
    popularity: 79,
    createdAt: "2026-04-01",
    progress: "not-started",
    testCases: [
      {
        name: "Sample 1",
        input: "[2, 3, 8, 4, 6]\n3\n5",
        expectedOutput: "1",
      },
      {
        name: "Sample 2",
        input: "[1, 2, 3]\n2\n5",
        expectedOutput: "-1",
      },
    ],
  },
  {
    id: "challenge-017",
    slug: "retention-cohorts",
    title: "Retention Cohorts",
    difficulty: "Medium",
    summary: "Write a SQL query that reports day-seven user retention by signup date.",
    description: [
      "A product analytics table stores one row per user activity event. You need to measure how many users from each signup date returned exactly seven days later.",
      "Return signup_date, cohort_size, retained_users, and retention_rate ordered by signup_date ascending. The retention rate should be a decimal rounded to two places.",
    ],
    examples: [
      {
        title: "Small activity sample",
        input:
          "events(user_id, event_date, signup_date)\n(1, '2026-04-01', '2026-04-01')\n(1, '2026-04-08', '2026-04-01')\n(2, '2026-04-01', '2026-04-01')",
        output: "2026-04-01 | 2 | 1 | 0.50",
        explanation:
          "Two users signed up on April 1. Only one of them had activity exactly seven days later.",
      },
    ],
    constraints: [
      "The table name is events.",
      "event_date and signup_date are DATE columns.",
      "Each user may have multiple activity events on the same date.",
      "Return one row per signup date.",
    ],
    notes: [
      "Count distinct retained users so duplicate activity does not inflate the rate.",
    ],
    tags: ["Database", "Hash Table"],
    category: "SQL",
    kind: "sql",
    supportedLanguages: ["sql"],
    starterCodeByLanguage: createStarterCode("Retention Cohorts", ["sql"]),
    acceptanceRate: 57,
    estimatedMinutes: 26,
    attempts: 7180,
    popularity: 74,
    createdAt: "2026-04-06",
    progress: "not-started",
    testCases: [
      {
        name: "Sample 1",
        input:
          "events\n1 2026-04-01 2026-04-01\n1 2026-04-08 2026-04-01\n2 2026-04-01 2026-04-01",
        expectedOutput: "2026-04-01 | 2 | 1 | 0.50",
      },
    ],
  },
];
