export const PROFILE_DISPLAY_NAME_LIMIT = 60;
export const PROFILE_BIO_LIMIT = 255;
export const PROFILE_SETTINGS_TOAST_DURATION_MS = 2800;
export const PROFILE_SETTINGS_SAVE_INDICATOR_DELAY_MS = 180;
export const PROFILE_SETTINGS_SAVE_INDICATOR_MIN_VISIBLE_MS = 520;
